__all__ = ["st_exchange_id.py", # draft 21
           "st_compound.py",
           "st_create_session.py",
           "st_destroy_session.py",
           "st_destroy_clientid.py",
           "st_reclaim_complete.py",
           "st_secinfo_no_name.py",
           "st_secinfo.py",
           "st_sequence.py",
	   "st_trunking.py",
           "st_open.py",
           "st_verify.py",
           "st_getdevicelist.py",
           "st_lookupp.py",
           "st_rename.py",
           "st_putfh.py",
           "st_reboot.py",
##            "st_lookup.py",
           ##################
           "st_block.py",
##           "st_debug.py",
##           "st_loop",
           "st_current_stateid.py",
           ]
