# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.35
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _gssapi
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ptr2str = _gssapi.ptr2str
GSS_S_COMPLETE = _gssapi.GSS_S_COMPLETE
GSS_S_CONTINUE_NEEDED = _gssapi.GSS_S_CONTINUE_NEEDED
DELEG_FLAG = _gssapi.DELEG_FLAG
MUTUAL_FLAG = _gssapi.MUTUAL_FLAG
REPLAY_FLAG = _gssapi.REPLAY_FLAG
SEQUENCE_FLAG = _gssapi.SEQUENCE_FLAG
CONF_FLAG = _gssapi.CONF_FLAG
INTEG_FLAG = _gssapi.INTEG_FLAG
ANON_FLAG = _gssapi.ANON_FLAG
PROT_READY_FLAG = _gssapi.PROT_READY_FLAG
TRANS_FLAG = _gssapi.TRANS_FLAG

def importName(*args):
  """importName(string name, gss_OID name_type=HOSTBASED_SERVICE) -> name"""
  return _gssapi.importName(*args)

def initSecContext(*args):
  """initSecContext(gss_name_t name, gss_ctx_id_t *context=None, string token=None, gss_cred_id_t cred=None, gss_OID mech=krb5oid, int flags=0, int time=0, gss_channel_bindings_t chan=None) -> context, mech, token, flags, time"""
  return _gssapi.initSecContext(*args)

def acceptSecContext(*args):
  """initSecContext(gss_name_t name, gss_ctx_id_t *context=None, string token=None, gss_cred_id_t cred=None, gss_OID mech=krb5oid, int flags=0, int time=0, gss_channel_bindings_t chan=None) -> context, mech, token, flags, time"""
  return _gssapi.acceptSecContext(*args)

def getMIC(*args):
  """getMIC(gss_ctx_id_t context, string msg, int qop) -> string checksum"""
  return _gssapi.getMIC(*args)

def verifyMIC(*args):
  """verifyMIC(gss_ctx_id_t context, string msg, string checksum) -> qop"""
  return _gssapi.verifyMIC(*args)

def wrap(*args):
  """verifyMIC(gss_ctx_id_t context, string msg, string checksum) -> qop"""
  return _gssapi.wrap(*args)

def unwrap(*args):
  """verifyMIC(gss_ctx_id_t context, string msg, string checksum) -> qop"""
  return _gssapi.unwrap(*args)

cvar = _gssapi.cvar
HOSTBASED_SERVICE = cvar.HOSTBASED_SERVICE
krb5oid = cvar.krb5oid

